# Render Blueprint for NoteHub Backend
# This file configures automatic deployment of the FastAPI backend with PostgreSQL
# Documentation: https://render.com/docs/blueprint-spec

services:
  # FastAPI Backend Service
  - type: web
    name: notehub-backend
    runtime: python
    region: frankfurt  # Options: oregon, frankfurt, ohio, singapore
    plan: free  # Free tier: 750 hours/month, sleeps after 15min inactivity
    branch: master  # Deploy from master branch
    rootDir: backend  # Application root directory
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /docs  # Render pings this to check if service is up
    
    envVars:
      # Database URL - automatically set from the database below
      # Render provides postgresql:// but we need postgresql+asyncpg://
      # This is handled in app/core/config.py
      - key: DATABASE_URL
        fromDatabase:
          name: notehub-db
          property: connectionString
      
      # Secret key for JWT tokens - auto-generated by Render
      # To set custom key: remove generateValue and add value: "your-key"
      - key: SECRET_KEY
        generateValue: true
      
      # CORS origins - UPDATE AFTER DEPLOYING FRONTEND!
      # Add your Vercel/Netlify URL here
      - key: CORS_ORIGINS
        value: "http://localhost:5173,http://localhost:3000,https://your-frontend.vercel.app"
    
    # Auto-deploy on push to master branch
    autoDeploy: true

# PostgreSQL Database
databases:
  - name: notehub-db
    databaseName: notehub
    user: notehub
    plan: free  # Free: 90 days, 1GB storage, then $7/month
    region: frankfurt  # Should match service region for better performance
    ipAllowList: []  # Empty = allow all IPs (required for Render services)
